#!/usr/bin/bash
#Find out by doing something like:
#curl -L radiofeeds.co.uk/query.asp?feedme=jazz+fm | sed -n "/jazz-/p" | sed "s/<a href.*http/url=http/" | sed "s/\">//"
#curl -L radiofeeds.co.uk/query.asp?feedme=jazz+fm | sed -n "/jazzhigh-/p" | sed "s/<a href.*http/url=http/" | sed "s/\">//"
#curl -L radiofeeds.co.uk/query.asp?feedme=absolute | sed -n "/absoluteradio-/p" | sed "s/<a href.*http/url=http/" | sed "s/\">//">>findjazz
#
#These worked
#
url1=http://www.radiofeeds.net/playlists/bauer.pls?station=jazz-mp3
url2=http://www.radiofeeds.net/playlists/bauer.pls?station=jazzhigh-aac
url3=http://www.radiofeeds.net/playlists/bauerflash.pls?station=absoluteradio-mp3
url4=http://www.radiofeeds.net/playlists/bauerflash.pls?station=absoluteradio-aac
if [ -f newbauer.m3u ]
then
	rm newbauer.m3u
fi
touch newbauer.m3u
now=$(date +%s)
echo $now
for i in $url1 $url2 $url3 $url4; do
#file=$(curl -L "$i" | sed -n "s/File1=//;s/key=.*/key=$now/p")
file=$(curl -L "$i" | sed -n "s/File1=//p")
file=$(echo $file | sed "s/\n//;s/\r//")
echo -e "\tNeed to get file:\e[34m $file \e[0m"
printf "\tNeed to get file:\e[34m %s \e[0m\n" $file
codeback=$(curl -LIs $file -o /dev/null -w "%{http_code}\n")
echo $codeback
if [ $codeback != '200' ]
then
echo -e "\tNo File:\e[34m $file \e[0m here"
printf "\tNo File:\e[34m %s \e[0m here\n" $file
else
	echo OK
	mpc add $file
	echo $file >> newbauer.m3u
fi
done
for i in $(sed "s/\&.*//" newbauer.m3u |  awk -F= '/bauer/ { print $2; }'); do echo $i to $now;sed -i "s/$i/$now/" newbauer.m3u; done
