#!/bin/bash
tim=$(date +%d_%m_%Y)
file=/home/pi/sound/Brownswood_Basement
length=$(echo 1234|awk '{ print 60*60*4 }') #4 hour programme
echo $length
ffmpeg -i "http://worldwidefm.out.airtime.pro:8000/worldwidefm_a" -t $length -c copy $file$tim.mp3
id3v2 -y $(date +%Y) $file$tim.mp3
id3v2 -a "$(date +%d-%B) Recording" $file$tim.mp3
id3v2 -t "World Wide FM ($length secs)" $file$tim.mp3
id3v2 -A $(date +%H:%M:%S) $file$tim.mp3
id3v2 -l $file$tim.mp3
cp $file$tim.mp3 /home/pi/Music/wfm1.mp3
mpc --wait update 

#Change the date using this
#cp $file$tim.mp3 $file$(date -d @$(date +%s |awk '{ print $0-24*3600 }') +%d_%m_%Y | awk '{ print $0".mp3" }')
