#!/bin/bash
#41 06 * * 3 /home/pi/sound/names_in_songs > name`date +\%d-\%m-\%Y-\%T`
#11 14 * * 3 /home/pi/sound/names_in_songs names2.m4a > name`date +\%d-\%m-\%Y-\%T`
#start time is around 6:40am and 14:10
file=${1:-names.m4a}
length=${2:-27\:00}
colin=${3:-pi}
trixie64=${4:-trixie64}
radio6="http://lsn.lv/bbcradio.m3u8?station=bbc_6music&bitrate=320000"
if [ -f /home/$colin/Music/$file ]; then
rm /home/$colin/Music/$file
fi
echo Start $(date)
ffmpeg -to $length -i "$radio6" -c copy  /home/$colin/Music/$file
len=$(ls -l /home/$colin/Music/$file | awk '{ print $5 }')
if [ -f /home/$colin/Music/$file ]; then
  echo $len file made /home/$colin/Music/$file
  if [ $len -lt 50000 ]; then 
    echo try again
    rm /home/$colin/Music/$file
    ffmpeg -to $length -i "$radio6" -c copy  /home/$colin/Music/$file
  fi
else
  echo nofile /home/$colin/Music/$file
fi
if [ $(uname -n) != $trixie64 ]; then
  scp /home/$colin/Music/$file pi@$trixie64.local:/home/pi/Music
  export MPD_HOST=$trixie64.local
fi
echo Finish $(date)
#mpc --wait update
