#!/bin/bash
#38 06 * * 3 /home/pi/sound/names_in_songs
#38 14 * * 3 /home/pi/sound/names_in_songs names2.m4a
#start time is around 6:40am
file=${1:-names.m4a}
rm /home/pi/Music/$file
ffmpeg -i "https://lstn.lv/bbcradio.m3u8?station=bbc_6music&bitrate=320000" -t 600 -c copy /home/pi/Music/$file
