#!/bin/bash
now="$(date +%d_%m_%Y_%T)_$(uname -m -n -s|sed 's/ /-/'g)"
echo $now
server_place=new64
file=record$now.mp3
length=${1:-03\:00\:00}
rm /home/colin/sound/"$file"
#ffmpeg -i "https://lstn.lv/bbcradio.m3u8?station=bbc_6music&bitrate=96000" -ab 320k -to $length /home/colin/sound/"$file"
echo Start $(date)
ffmpeg -to $length -i "https://lstn.lv/bbcradio.m3u8?station=bbc_6music&bitrate=320000" -ab 320k /home/colin/sound/"$file"
echo End $(date)
id3v2 -c "$(uname -a)" -y $(date +%Y) -A "$(uname -a)" -t "6 music at $now" -a "Length: $length " /home/colin/sound/"$file"
id3v2 -l /home/colin/sound/"$file"
cp /home/colin/sound/"$file" /home/colin/Music
if [ $(uname -n) != $server_place ]; then
	scp /home/colin/sound/"$file" pi@$server_place.local:~/Music
	export MPD_HOST=$server_place.local
fi
mpc --wait update
mpc add "$file"
