#!/bin/bash
now=$(date +%d_%m_%Y_%T)
file=record$now.mp3
length=${1:-15\:00}
rm /home/pi/sound/"$file"
echo Start $(date)
ffmpeg -i "https://lstn.lv/bbcradio.m3u8?station=bbc_6music&bitrate=320000" -to $length  -ab 320k /home/pi/sound/"$file"
echo End $(date)
id3v2 -c"$(uname -a)" -t "6 music at $now" -a "Length: $length" /home/pi/sound/"$file"
id3v2 -l /home/pi/sound/"$file"
scp /home/pi/sound/"$file" pi@new64.local:/home/pi/Music/"$file" 
mpc -h new64.local --wait update
mpc -h new64.local add $file
mpc -h new64.local --wait update
mpc -h new64.local playlist
