#!/usr/bin/bash
#This must be run in the playlist directory!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#I installed this stuff (probably just bluez stuff is enough) and made .asoundrc file for home directory
#sudo apt install pipewire-audio pulseaudio-module-bluetooth
#sudo apt install  pulseaudio-module-bluetooth
#sudo apt install bluez bluez-alsa bluez-alsa-utils bluez bluez-tools

#defaults.bluealsa {
#interface "hci0"
#device "E4:61:F4:9E:B6:50" # this is the address of the bluetooth headphone found using bluetoothctl and scan on
#profile "a2dp"
#}

#Need this in mpd.conf
#audio_output {
#	type		"alsa"
#	name		"ALSA"
#	device		"bluealsa"	# optional
##mixer_type      "hardware"	# optional
##	mixer_device	"default"	# optional
##	mixer_control	"PCM"		# optional
##	mixer_index	"0"		# optional
#}

#Another .asoundrc file
#defaults.bluealsa {
#        interface "hci0"
#        device "E4:61:F4:9E:B6:50" # this is the address of the bluetooth headphone found using bluetoothctl and scan on
#        profile "a2dp"
#}
#pcm.!default {
#        type plug
#        slave.pcm "dmixer"
#}
#pcm.dmixer  {
#        type dmix
#        ipc_key 1024
#        slave {
#                pcm "hw:0,0"
#                period_time 0
#                period_size 1024
#                buffer_size 4096
#                rate 44100
#        }
#        bindings {
#                0 0
#                1 1
#        }
#}
#ctl.dmixer {
#        type hw
#        card 0
#}

playlistfile=${1:-newlist.m3u}
now=$(date +%s)

if [ -f $playlistfile ] 
then
	rm $playlistfile
fi

mpc save $(echo $playlistfile|sed "s/.m3u//")

for i in $(sed "s/\&.*//" $playlistfile |  awk -F= '/bauer/ { print $2; }'); do echo Old time;date --date=@$i;echo $i to $now; echo After $((($now-$i)/3600)) hours; sed -i "s/$i/$now/" $playlistfile; done

mpc clear
mpc load $(echo $playlistfile|sed "s/.m3u//")

